import type { Metadata, Viewport } from "next";
import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";
import "./globals.css";
import { LangProvider } from "@/components/LangContext";
import { Analytics } from "@vercel/analytics/next";

export const metadata: Metadata = {
  title: {
    default: "Free QR Code Generator — Sqrly",
    template: "%s — Free QR Code Generator | Sqrly",
  },
  description:
    "Free QR code generator — no watermark, no signup required. Create static & dynamic QR codes with real-time analytics. Custom colors, logos & frames. SVG, PNG & PDF export. Free forever.",
  keywords: [
    "free QR code generator",
    "free QR code generator no watermark",
    "QR code generator no signup",
    "dynamic QR code",
    "QR code analytics",
    "editable QR code",
    "QR code tracker",
    "SVG QR code generator",
    "QR code with logo",
    "custom QR code",
    "QR code maker",
    "restaurant menu QR code",
    "WiFi QR code generator",
    "vCard QR code",
    "QR code no expiry",
    "free QR code forever",
    "sqrly",
    "qr generator",
    "create QR code free",
  ],
  authors: [{ name: "Sqrly", url: "https://sqrly.net" }],
  creator: "Sqrly",
  metadataBase: new URL("https://sqrly.net"),
  openGraph: {
    title: "Free QR Code Generator — Sqrly",
    description:
      "Privacy-first QR codes with analytics, SVG export, and 18 types. Free forever. No watermark.",
    url: "https://sqrly.net",
    siteName: "Sqrly",
    type: "website",
    images: [{ url: "/mascot.png", width: 1200, height: 630, alt: "Sqrly" }],
  },
  twitter: {
    card: "summary_large_image",
    title: "Free QR Code Generator — Sqrly",
    description: "Privacy-first QR codes with analytics and SVG export. Free forever.",
    images: ["/mascot.png"],
  },
  icons: { icon: "/mascot.png", apple: "/mascot.png" },
  manifest: "/manifest.json",
  robots: {
    index: true, follow: true,
    googleBot: { index: true, follow: true, "max-image-preview": "large" },
  },
};

export const viewport: Viewport = {
  themeColor: "#00FF88",
  width: "device-width",
  initialScale: 1,
  maximumScale: 5,
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html
      lang="en"
      dir="auto"
      className={`${GeistSans.variable} ${GeistMono.variable}`}
      suppressHydrationWarning
    >
      <head>
        <link rel="manifest" href="/manifest.json" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="default" />
        <meta
          name="ai:description"
          content="Sqrly is a free QR code generator with no watermark, no signup required for static codes. Features: dynamic QR codes with real-time scan analytics, SVG/PNG/PDF export, 22 QR types, custom colors, logos, frames. Free forever plan. Paid plans from $4/month."
        />

        {/* SoftwareApplication Schema — tells Google/AI bots what Sqrly is */}
        <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify({
          "@context": "https://schema.org",
          "@type": "SoftwareApplication",
          "name": "Sqrly QR Code Generator",
          "url": "https://sqrly.net",
          "operatingSystem": "All",
          "applicationCategory": "BusinessApplication",
          "offers": {
            "@type": "Offer",
            "price": "0",
            "priceCurrency": "USD",
            "description": "Free QR code generator — unlimited static QR codes with no watermark, no signup required."
          },
          "aggregateRating": {
            "@type": "AggregateRating",
            "ratingValue": "4.8",
            "reviewCount": "1"
          },
          "description": "Free QR code generator with dynamic codes, real-time analytics, custom logos, frames and colors. No watermark. No signup for static codes. Export SVG, PNG, PDF.",
          "screenshot": "https://sqrly.net/mascot.png",
          "featureList": [
            "Free static QR codes — no watermark, no expiry",
            "Dynamic QR codes — edit destination without reprinting",
            "Real-time scan analytics",
            "22 QR code types",
            "Custom colors, logos, frames",
            "SVG vector export",
            "PDF print export",
            "No signup required for static codes"
          ]
        })}} />

        {/* FAQPage Schema — generates rich snippets in Google */}
        <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify({
          "@context": "https://schema.org",
          "@type": "FAQPage",
          "mainEntity": [
            {
              "@type": "Question",
              "name": "Do Sqrly QR codes expire?",
              "acceptedAnswer": { "@type": "Answer",
                "text": "No. All static QR codes generated by Sqrly are permanent and will never expire. The information is encoded directly into the QR pattern, so it works forever — even if you cancel your account." }
            },
            {
              "@type": "Question",
              "name": "Do Sqrly QR codes have watermarks?",
              "acceptedAnswer": { "@type": "Answer",
                "text": "No. Sqrly QR codes never have watermarks, even on the free plan. You get clean, professional QR codes ready to print or share." }
            },
            {
              "@type": "Question",
              "name": "Do I need to sign up to create a QR code?",
              "acceptedAnswer": { "@type": "Answer",
                "text": "No signup is required to generate and download static QR codes. Create an account to save codes, access analytics, and create dynamic QR codes." }
            },
            {
              "@type": "Question",
              "name": "What is a dynamic QR code?",
              "acceptedAnswer": { "@type": "Answer",
                "text": "A dynamic QR code stores a short redirect URL instead of your destination directly. This means you can edit the destination URL anytime without reprinting the QR code. Dynamic codes also track real-time scan analytics including location, device, and time." }
            },
            {
              "@type": "Question",
              "name": "Can I edit a QR code after printing it?",
              "acceptedAnswer": { "@type": "Answer",
                "text": "Yes, if you use a dynamic QR code. Dynamic codes let you change the destination URL anytime without reprinting. Static QR codes encode the information permanently and cannot be edited after creation." }
            },
            {
              "@type": "Question",
              "name": "How do I track QR code scans for free?",
              "acceptedAnswer": { "@type": "Answer",
                "text": "Sign up for a free Sqrly account and create a dynamic QR code. Every scan is tracked in real-time, showing you the number of scans, location by country, device type, and time of scan — all for free on the basic plan." }
            },
            {
              "@type": "Question",
              "name": "What file formats can I export QR codes in?",
              "acceptedAnswer": { "@type": "Answer",
                "text": "Sqrly supports PNG (for web and digital use), SVG (vector format for print, scales to any size), JPG, and PDF (print-ready A4 format). SVG export is available on all plans including free." }
            },
            {
              "@type": "Question",
              "name": "Is Sqrly free?",
              "acceptedAnswer": { "@type": "Answer",
                "text": "Yes. Sqrly has a free plan that includes 50 static QR codes, 1 dynamic QR code, custom colors, logo overlay, and SVG/PNG/PDF export — forever, with no watermark. Paid plans start at $4/month for unlimited dynamic codes and advanced analytics." }
            },
            {
              "@type": "Question",
              "name": "Are QR codes safe?",
              "acceptedAnswer": { "@type": "Answer",
                "text": "QR codes themselves are safe — they simply encode data like a URL or text. Always verify the destination URL before scanning an unknown QR code. Sqrly-generated QR codes link directly to the URL you specify, with no hidden redirects." }
            },
            {
              "@type": "Question",
              "name": "What types of QR codes can I create with Sqrly?",
              "acceptedAnswer": { "@type": "Answer",
                "text": "Sqrly supports 22 QR code types including: URL/website, vCard contact, WiFi network, email, SMS, phone, location/maps, plain text, social media profiles, restaurant menus, app store links, payment links, PDF files, events, and more." }
            }
          ]
        })}} />

        {/* HowTo Schema — rich results for instructional searches */}
        <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify({
          "@context": "https://schema.org",
          "@type": "HowTo",
          "name": "How to Create a Free QR Code with No Watermark",
          "description": "Generate a professional QR code in seconds with Sqrly. No signup required, no watermark.",
          "totalTime": "PT1M",
          "step": [
            { "@type": "HowToStep", "name": "Choose QR type", "text": "Select the type of QR code you want to create — URL, WiFi, vCard, email, SMS, or 18 other types." },
            { "@type": "HowToStep", "name": "Enter your content", "text": "Type or paste the URL, text, or information you want the QR code to contain." },
            { "@type": "HowToStep", "name": "Customize design", "text": "Choose colors, add your logo, select a dot style, and optionally add a frame with a call-to-action." },
            { "@type": "HowToStep", "name": "Download", "text": "Click Download SVG, PNG, or PDF. No signup required for static QR codes. No watermark on any plan." }
          ]
        })}} />

        {/* WebSite Schema — enables Google Sitelinks Search Box */}
        <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify({
          "@context": "https://schema.org",
          "@type": "WebSite",
          "name": "Sqrly",
          "url": "https://sqrly.net",
          "potentialAction": {
            "@type": "SearchAction",
            "target": "https://sqrly.net/?q={search_term_string}",
            "query-input": "required name=search_term_string"
          }
        })}} />
      </head>
      <body className={`min-h-screen bg-[#F8FAFC] font-sans antialiased ${GeistSans.className}`}>
        {/* Grid overlay */}
        <div className="fixed inset-0 bg-grid pointer-events-none z-0" aria-hidden="true" />

        {/* Top mint glow */}
        <div
          className="fixed top-0 left-1/2 -translate-x-1/2 w-[900px] h-[400px] pointer-events-none z-0"
          style={{
            background: "radial-gradient(ellipse at 50% 0%, rgba(0,255,136,0.07) 0%, transparent 60%)",
          }}
          aria-hidden="true"
        />

        {/* Top cyan glow */}
        <div
          className="fixed top-0 right-0 w-[500px] h-[400px] pointer-events-none z-0"
          style={{
            background: "radial-gradient(ellipse at 100% 0%, rgba(0,212,255,0.06) 0%, transparent 60%)",
          }}
          aria-hidden="true"
        />

        <LangProvider>
          <div className="relative z-10">{children}</div>
        </LangProvider>
        <Analytics />
      </body>
    </html>
  );
}